---
title: This, I believe
author: ""
date: '2020-11-04'
---

I believe that Earth is the only planet our species can expect to thrive on for the imaginable future.

I believe that human activities are threatening our planet's viabilility as a home for us and for other forms of life.

I believe that human ingenuity can devise ways for us to reduce or eliminate those threats and enable us to continue to prosper.

I believe that doing so requires those of us in the wealthiest countries to lead.

I believe that we must make greater sacrifices than others, we must show resolve and discipline, and we must lead by example.

I believe that Americans have the courage to lead and the strength to make these sacrifices.

I believe that a small, powerful, and vocal minority of Americans and allied foreign interests undermine that courage and diminish that strength.

I believe that many people are terrified of the future and mask their terror in anger and aggression.

I believe that others think their considerable wealth can protect them from an uncertain future.

I believe that these people personally benefit from undermining American unity.

I believe that the fearful and angry command our attention and sap our energy.

I believe that the self-serving and cynical provide no path to a better tomorrow for anyone but themselves.

I believe that America can be great only if it can admit where and when and why it is not; Only then can we mend what is broken.

I believe that without courage there is no honesty; without honesty, there is no truth; without truth, there is no justice; without justice, there is no peace; and without peace, there is no promise.

This, I believe.
