---
title: Home of the meek
author: ""
date: '2020-05-13'
categories: [politics]
---

There is no doubt that the corona virus pandemic provides the entire world a terrifying reminder that human life and civilization is vulnerable to the whims of uncaring forces of nature.
There is also no doubt that some countries, or more precisely, some cultures appear much better equipped than others to confront the challenges of the current moment.
Significant parts of American culture are not among the well-equipped.

Observe, for example, the case of Nebraska, where meatpacking plants have had significant corona virus outbreaks, but companies and public officials have been reluctant to provide information about the extent of the problem (https://www.washingtonpost.com/business/2020/05/12/nebraska-coronavirus-case-numbers-meatpacking/?utm_campaign=wp_post_most&utm_medium=email&utm_source=newsletter&wpisrc=nl_most) until pressured to do so by the fear of embarrassment.
Can we agree in this bitterly divided nation that all of us are afraid of the very same things -- that the virus might harm us or those we care about and that a prolonged quarantine might destroy a way of life we have come to enjoy?
I submit to you that until those parts of American culture that vigorously deny their fear can face it squarely -- rather than mask it with anger and bravado -- we'll continue to provide the world  object lessons in how not to respond.

Facts, data, evidence, reason, discipline, skepticism, sacrifice, generosity, honor, resolve, and courage.
These are what we need now, from everyone everywhere.
Make Americans brave again.
Please.
