---
title: Morse, of course
author: ""
date: '2020-05-13'
categories: [ham radio]
---

I've been a ham for only a few years.
In that time, I've enjoyed sampling the hobby's many facets.
When I first heard about ham radio as a boy, the thrills were mostly about talking by voice and CW (Morse code) to stations around the world.
Now there are dozens of digital (computer-to-computer) modes, styles of operating, and bands to operate on.

I learned a bit of Morse code back when I was first licensed in 1993.
But in my second reincarnation as a ham, the code requirements had been dropped, and so there was no compelling reason to learn it.
Except that I wanted to.
For reasons I don't quite understand, I'm drawn to learn skills that don't have much practical use but have a venerable history and still attract enthusiasts.
Playing clawhammer banjo is one, and learning to operate CW (the transmission mode that turns Morse code into radio waves) is another.

So, after starting one of the [CW Academy](https://cwops.org/cw-academy/) courses in January 2019, I tried again this year. 
I took the Beginner class earlier this year, and I'm now 2/3 of the way through the Basic class.
The instructors are fantastic.
The curriculum is well-structured and useful.
I've made significant progress.
But, boy is it hard!

When I was younger, any number of new things came to me rather easily.
Not everything, but many things.
And I grew accustomed to thinking I was a fast learner.
Welcome to middle age.
As with learning the banjo, or learning lines or music for a theatrical production, I find that I have to work much, much harder than I did when I was younger.
Or alternatively, I have to adjust my expectations about how much progress I'll see with the amount of work I put in.

It's also humbling, but gratifying to be on the other side of the teaching lectern.
I think all professors should find ways to be students, again.
Puts things into perspective.

And I'm sure that when all the dits and dahs finally sound like words to my brain--they're starting to, every now and then--I'll be glad I stayed the course.
There's something magical about reaching out to another person and talking with them over the airwaves, and especially when it's in a 'language' that started the age of radio communication.

