---
title: Seeing through the fog
author: ""
date: '2019-11-17'
categories: [politics]
---

I understand why Republican partisans want to confuse the public.
But this is crystal clear.

No candidate for elected office in the United States should **ever** seek or receive help from foreign countries to win an election.
Not ever.
Period.

In taking office, a president pledges (or affirms) to "preserve, protect, and defend the Constitution."
Senators and Congressional Representatives pledge (or affirm) to "support and defend the Constitution of the United States against all enemies, foreign and domestic..."

Mr. Trump has now at least twice asked for help from a foreign power to gain political advantage over an opponent, once as a candidate, and at least once as president.
The asking itself is unmistakably, incontrovertibly, and indefensibly wrong.

Seeking foreign interference subverts the integrity of our elections, undermines the Constitution, and violates the presidential oath of office.

A president must uphold the rule of law not advance the law of rulers.
He is unfit.
He must be impeached and removed from office.
Failing to do so represents a violation of the oath of office taken by Senators and Representatives alike to "defend the Constitution against all enemies, foreign and domestic."

There is no fog here, just strategically and cynically blown smoke.
