---
title: "Choosing sides"
date: 2023-11-09
---

My department sent around an email earlier today announcing an event about the crisis in Gaza titled "Genocide in Gaza: A teach-in".

Here was my reply to the person who sent the announcement:

>To host a teach-in about the conflict in Gaza with the title “Genocide in Gaza” suggests that you and the other organizers have already taken sides in a dispute that is astonishingly complex and tragically long-standing.
>
>When I suggested in the faculty meeting that you need not send more emails about this issue, that it was not necessary for the department or the university to take a stand, **as an organization**, on this topic, this is not at all what I expected.
>
>The deaths of thousands of Palestinians in Gaza is horrendous and deplorable. Peace-loving people of all faiths and no faith at all must work tirelessly to end the violence there.
>
>And, the deliberate murder of more than 1,400 people, mostly Jews, by Hamas is a crime against humanity. It cannot be excused and must not be diminished.
>
>To call the war in Gaza genocide is deeply, profoundly wrong. The term genocide did not exist until it was invented in 1944 by a Polish Jew specifically to describe the systematic murder of Jews by the Nazis. The 10/7 attack was the largest killing of Jews since the Holocaust, and it was entirely in keeping with the mission of Hamas, as stated in its charter. That charter specifically calls for genocidal actions: The killing of Jews and the destruction of Israel. It is no irony that some advocates for Palestinians want to ignore these facts about Hamas and blur the meaning of genocide.
>
>This department and this institution exist to support the free and civil exchange of ideas about controversial topics, including this one. But it is wrong for the department and institution to take sides in a dispute of this magnitude and complexity. And it is deeply insensitive to many Jewish faculty, staff, and students who are still grieving the terrible events of 10/7 and the violence that has ensued since.

