---
title: "I never metaphysics"
date: 2015-08-14T00:00:00
categories: ["poetry"]
---

<p>
it's like fireworks, dad.</br>
you said the colors and patterns come from all the minerals.</br>
their making a mutual arrangement designed to ignite and illuminate.
</p>

<p>
you said the designers crafted this one boomy blue and that one sparkly-white.</br>
this cascade brilliant, that smiley face a dud.</br>
</p>

<p>
flying high or bursting low, it's all in the timing</br>
and atmospheric conditions.</br>
don't forget chemistry and physics.</br>
human ingenuity (and error).</br>
some are dampened or damaged in transit.
</p>

<p>
do you think they know it's all ashes at the end?</br>
maybe.</br>
probably.</br>
but what a ride.</br>
what a show.</br>
I don't care if the music is synchronized.</br>
ooh.</br>
ahh.
</p>

::: {.callout-note}

I wrote this poem after visiting my friend, Lloyd Short, in the hospital.
He told me that he was dying, and only had a few days left.
In fact, I was the last person who was not a family member to see him.

It was my honor to recite this poem at Lloyd's memorial service.

I hope that people who knew and loved Lloyd see him here.

:::
