---
title: "We are...not teammates"
date: 2023-09-15
categories:
  - Academia
  - Gilmore U
---

For several years now I've argued that unlike the sports for which my institution is most famous, the scholarly side of the shop is *not* a team effort, not in the least.

Don't get me wrong, my academic colleagues are (mostly) collegial and congenial, and even the prickly ones aren't especially so.
And though we compete fiercely for space, students, grants, renown, raises, attention and favors from higher-ups, we also (mostly) deny that we are competitors.

But reality bites whether or not we see the teeth.

In reality, academic institutions like mine are business incubators or venture capitalists. They are run by people who seek concrete returns on investment (ROIs).
Just like a business incubator, seed investments are made in *individual* investigators whose advancement depends on the construction of vertically integrated enterprises with their name at the top.
Credit for team projects is divided into portions even when the whole is far more than the sum of the parts.
Individual researchers are expected to learn, without training, orientation, or support, how to navigate a gigantic bureaucracy in order to build their individual brands.

A speaker at a recent event I attended remarked that greater communication among researchers working on similar problems would accelerate discovery, especially in cutting edge fields.
Too often, the speaker observed, people down the hall or across campus from one another are working on the same problems without knowledge of one another's efforts.
It's hard to disagree.
But when researchers demand firewalls to prevent their colleagues down the hall from stealing intellectual property, it's also not hard to understand why that communication doesn't happen.

Academic scholarship is not a team sport.
And that's okay.
Not everyone likes team sports or teamwork for that matter.
I just wish we were more honest with ourselves and our trainees about this fundamental structural fact.
It makes all sorts of things about life here in the ivory tower much clearer, at least to me.
