---
title: This is personal
author: ""
date: '2020-11-11'
categories: [politics]
---

The Trump campaign is suing Centre County where I live and serve as an election official:

https://www.centredaily.com/news/politics-government/election/article247090102.html?ac_cid=DM321193&ac_bid=-1472755416

In State College East 3 Precinct 26, we have a longstanding tradition of helping every single voter, regardless of party affiliation.
Our neighborhood has permanent residents and more transient ones, usually Penn State students.
So, many of the voters who show up on election day, especially in a presidential election year, do so for the first time.
Some of them come to our precinct because that's the one in their neighborhood even though they might be registered in another precinct.
If they aren't registered in our precinct, we help them find out if they are registered and where they are registered.
That's not always easy to do, but we know which websites to have them check and how to advise them about their options.

More than 20 states offer same day voting and registration.
Pennsylvania is not one of them.
We do our best with the system we have.

This year, we had a small number of students show up who weren't registered in Pennsylvania at all.
We advised them they could only vote a provisional ballot and that it was extremely unlikely that their vote would ultimately be counted.
Most chose to vote anyway, just in case there was a chance that their vote might count.
So, we helped these voters cast a provisional ballot, putting the decision about which ballots would ultimately be counted in the final in the hands of our county's election board.
Most importantly, we did not stand in the way of any voter casting a ballot.

We do these things in our precinct because we believe that every voter counts even if every single vote does not.
We do these things because many of us are educators, and we believe that encouraging habits of civic engagement are part of the legacy we want to leave.
We do these things because we believe that our union is stronger when more people participate in decisions about who should lead.
We do this because powerful forces throughout the history of our country have tried to restrict access to the ballot box and those forces are still active today.
We do these things because we believe that the *process* is more important than the *outcome*.
We do these things because they reflect what the Founders meant when they described their motivations for establishing the Constitution:

"...to form a more perfect union, establish justice, ensure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity..."

Our union is far from perfect, justice is not always done, and we are far from tranquil.
But the actions by Mr. Trump and his supporters to undermine the integrity of the election--before it had occurred and in its aftermath--are deeply and profoundly wrong.
To allege voting fraud without any actual evidence undermines the common defense, erodes the general welfare, and threatens the blessings of liberty.
And for election officials like me who work hard to ensure a fair and just voting process for everyone, the allegations are more than a little personal.

