---
title: This is great
author: ""
date: '2021-02-13'
categories: [politics]
---

Perhaps like me you suspected that the red hats did not share your view of what makes America great.

<iframe width="560" height="315" src="https://www.youtube.com/embed/ERIbhsCzZwk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

We now know the depth of that disagreement.

Thanks to the methodical and patriotic work of the House impeachment managers, we know in terrifying detail how much worse 1/6 might have become. Already there were casualties, among mobsters and law enforcement alike, shot, bludgeoned, or crushed to death. 

Blue lives matter, except of course when they do not. Especially when their loss does not fit an expedient narrative.

<iframe width="560" height="315" src="https://www.youtube.com/embed/rbukVhEih58" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

These unconscionable acts of aggression against the foundations of our democracy by leaders and citizens alike are great only to tyrants and knaves.

Frum has observed that [complicity](https://www.theatlantic.com/ideas/archive/2021/02/there-is-no-defenseonly-complicity/617996/) or conviction are the only choices for senators terrified of the beast their cowardice has created. Will worries that only [louts](https://www.washingtonpost.com/opinions/will-senate-republicans-allow-their-louts-to-rule-the-party/2021/02/11/ce082db6-6caf-11eb-9ead-673168d5b874_story.html) will remain in a party perhaps once grand but no longer.

I worry that senators will soon choose what vision of greatness they endorse and not enough will choose wisely.
